package cn.yuntk.radio.ibook.dbdao.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.yuntk.radio.ibook.bean.DownloadBookInfo;
import cn.yuntk.radio.ibook.bean.DownloadMusicInfo;
import cn.yuntk.radio.ibook.bean.ListenerBookInfo;
import cn.yuntk.radio.ibook.bean.ListenerMusicInfo;
import cn.yuntk.radio.ibook.bean.Music;
import cn.yuntk.radio.ibook.bean.TCAlbumTable;
import cn.yuntk.radio.ibook.bean.TCLastListenerTable;
import cn.yuntk.radio.ibook.bean.TCListenerTable;

import cn.yuntk.radio.ibook.dbdao.local.DownloadBookInfoDao;
import cn.yuntk.radio.ibook.dbdao.local.DownloadMusicInfoDao;
import cn.yuntk.radio.ibook.dbdao.local.ListenerBookInfoDao;
import cn.yuntk.radio.ibook.dbdao.local.ListenerMusicInfoDao;
import cn.yuntk.radio.ibook.dbdao.local.MusicDao;
import cn.yuntk.radio.ibook.dbdao.local.TCAlbumTableDao;
import cn.yuntk.radio.ibook.dbdao.local.TCLastListenerTableDao;
import cn.yuntk.radio.ibook.dbdao.local.TCListenerTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadBookInfoDaoConfig;
    private final DaoConfig downloadMusicInfoDaoConfig;
    private final DaoConfig listenerBookInfoDaoConfig;
    private final DaoConfig listenerMusicInfoDaoConfig;
    private final DaoConfig musicDaoConfig;
    private final DaoConfig tCAlbumTableDaoConfig;
    private final DaoConfig tCLastListenerTableDaoConfig;
    private final DaoConfig tCListenerTableDaoConfig;

    private final DownloadBookInfoDao downloadBookInfoDao;
    private final DownloadMusicInfoDao downloadMusicInfoDao;
    private final ListenerBookInfoDao listenerBookInfoDao;
    private final ListenerMusicInfoDao listenerMusicInfoDao;
    private final MusicDao musicDao;
    private final TCAlbumTableDao tCAlbumTableDao;
    private final TCLastListenerTableDao tCLastListenerTableDao;
    private final TCListenerTableDao tCListenerTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadBookInfoDaoConfig = daoConfigMap.get(DownloadBookInfoDao.class).clone();
        downloadBookInfoDaoConfig.initIdentityScope(type);

        downloadMusicInfoDaoConfig = daoConfigMap.get(DownloadMusicInfoDao.class).clone();
        downloadMusicInfoDaoConfig.initIdentityScope(type);

        listenerBookInfoDaoConfig = daoConfigMap.get(ListenerBookInfoDao.class).clone();
        listenerBookInfoDaoConfig.initIdentityScope(type);

        listenerMusicInfoDaoConfig = daoConfigMap.get(ListenerMusicInfoDao.class).clone();
        listenerMusicInfoDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        tCAlbumTableDaoConfig = daoConfigMap.get(TCAlbumTableDao.class).clone();
        tCAlbumTableDaoConfig.initIdentityScope(type);

        tCLastListenerTableDaoConfig = daoConfigMap.get(TCLastListenerTableDao.class).clone();
        tCLastListenerTableDaoConfig.initIdentityScope(type);

        tCListenerTableDaoConfig = daoConfigMap.get(TCListenerTableDao.class).clone();
        tCListenerTableDaoConfig.initIdentityScope(type);

        downloadBookInfoDao = new DownloadBookInfoDao(downloadBookInfoDaoConfig, this);
        downloadMusicInfoDao = new DownloadMusicInfoDao(downloadMusicInfoDaoConfig, this);
        listenerBookInfoDao = new ListenerBookInfoDao(listenerBookInfoDaoConfig, this);
        listenerMusicInfoDao = new ListenerMusicInfoDao(listenerMusicInfoDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);
        tCAlbumTableDao = new TCAlbumTableDao(tCAlbumTableDaoConfig, this);
        tCLastListenerTableDao = new TCLastListenerTableDao(tCLastListenerTableDaoConfig, this);
        tCListenerTableDao = new TCListenerTableDao(tCListenerTableDaoConfig, this);

        registerDao(DownloadBookInfo.class, downloadBookInfoDao);
        registerDao(DownloadMusicInfo.class, downloadMusicInfoDao);
        registerDao(ListenerBookInfo.class, listenerBookInfoDao);
        registerDao(ListenerMusicInfo.class, listenerMusicInfoDao);
        registerDao(Music.class, musicDao);
        registerDao(TCAlbumTable.class, tCAlbumTableDao);
        registerDao(TCLastListenerTable.class, tCLastListenerTableDao);
        registerDao(TCListenerTable.class, tCListenerTableDao);
    }
    
    public void clear() {
        downloadBookInfoDaoConfig.clearIdentityScope();
        downloadMusicInfoDaoConfig.clearIdentityScope();
        listenerBookInfoDaoConfig.clearIdentityScope();
        listenerMusicInfoDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
        tCAlbumTableDaoConfig.clearIdentityScope();
        tCLastListenerTableDaoConfig.clearIdentityScope();
        tCListenerTableDaoConfig.clearIdentityScope();
    }

    public DownloadBookInfoDao getDownloadBookInfoDao() {
        return downloadBookInfoDao;
    }

    public DownloadMusicInfoDao getDownloadMusicInfoDao() {
        return downloadMusicInfoDao;
    }

    public ListenerBookInfoDao getListenerBookInfoDao() {
        return listenerBookInfoDao;
    }

    public ListenerMusicInfoDao getListenerMusicInfoDao() {
        return listenerMusicInfoDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public TCAlbumTableDao getTCAlbumTableDao() {
        return tCAlbumTableDao;
    }

    public TCLastListenerTableDao getTCLastListenerTableDao() {
        return tCLastListenerTableDao;
    }

    public TCListenerTableDao getTCListenerTableDao() {
        return tCListenerTableDao;
    }

}
